### ISSUE TITLE
디스코드 코드블록이 irc에서 보이게 하기

### ISSUE THREAD

**Issue by disjukr** [langdev/rendezvous#12]
<img width="505" alt="스크린샷 2019-05-16 오후 2 48 39" src="https://user-images.githubusercontent.com/690661/57829402-d3711680-77e9-11e9-85b9-f7cb59839fdf.png">
뭔가 코드를 첨부했다는 건 알겠는데 내용이 안보입니다.

**Comment by elizgarcia5** [comment]
zzz
